name: Python application

on:
  repository_dispatch:
    types: [on-demand-test]
  schedule:
    - cron:  '1 9,21 * * *'
  workflow_dispatch:
    
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v1
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run script
      run: |
        python dam_imabari.py
      env:
        TAMAGAWA_CK: ${{ secrets.TAMAGAWA_CK }}
        TAMAGAWA_CS: ${{ secrets.TAMAGAWA_CS }}
        TAMAGAWA_AT: ${{ secrets.TAMAGAWA_AT }}
        TAMAGAWA_AS: ${{ secrets.TAMAGAWA_AS }}
        UTENA_CK: ${{ secrets.UTENA_CK }}
        UTENA_CS: ${{ secrets.UTENA_CS }}
        UTENA_AT: ${{ secrets.UTENA_AT }}
        UTENA_AS: ${{ secrets.UTENA_AS }}
