name: Python application

on:
  repository_dispatch:
    types: [on-demand-test]
  schedule:
    - cron:  '10 9 * * *'
  workflow_dispatch:
    
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Run script
      run: |
        python dam_imabari.py
      env:
        TAMAGAWA_BT: ${{ secrets.TAMAGAWA_BT }}
        TAMAGAWA_CK: ${{ secrets.TAMAGAWA_CK }}
        TAMAGAWA_CS: ${{ secrets.TAMAGAWA_CS }}
        TAMAGAWA_AT: ${{ secrets.TAMAGAWA_AT }}
        TAMAGAWA_AS: ${{ secrets.TAMAGAWA_AS }}
